baseURL = 'https://cst-bg.net/'
locale = 'en-us'
title = 'CST company website'
theme = "hyde"



[params]
  description = "Professional software development company in Svilengrad, BULGARIA"
  # This section replaces the old top-level 'author'
  [params.author]
    name = "CST LTD"

[menu]
  [[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 15
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 20
  [[menu.main]]
    name = "Careers"
    url = "/careers/"
    weight = 25
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 30
  [[menu.main]]
    name = "Blog"
    url ="/blog/"
    weight = 40
  [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # This allows <iframe> tags for maps